#cloud-config
users:
  - default
  - name: astronaut
    ssh_import_id: None
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_public_key}
    sudo:
      - 'ALL=(ALL) NOPASSWD:ALL'
    shell: /bin/bash

packages:
  - unzip
  - curl

write_files:
  - path: /etc/ssh/sshd_config
    content: |
      Port ${ssh_port}
      ListenAddress 0.0.0.0
      ListenAddress ::
      LogLevel ERROR
      PermitRootLogin no
      ChallengeResponseAuthentication no
      UsePAM yes
      AllowAgentForwarding no
      GatewayPorts no
      X11Forwarding no
      KerberosAuthentication no
      PrintMotd no
      TCPKeepAlive yes
      ClientAliveInterval 3
      ClientAliveCountMax 3
      AcceptEnv LANG LC_*
      Subsystem       sftp    /usr/lib/openssh/sftp-server
      AllowUsers astronaut

runcmd:
  - 'systemctl restart sshd.service'
  # Install the latest AWS CLI.
  - 'curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"'
  - 'unzip awscliv2.zip'
  - './aws/install'
  # Associate allocated EIP with this instance.
  - 'aws ec2 --region ${region} associate-address --public-ip ${public_ip} --instance-id "$(curl http://169.254.169.254/latest/meta-data/instance-id)"'
  # Install nvm and node
  - 'wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash'
  - 'nvm install 16'
  - 'nvm use 16'
