name: Docker Build
on:
  release:
    branches:
      - master

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master
        with:
          repository: bjd2385/HqO

      # Cf. https://github.com/marketplace/actions/build-and-push-docker-images?version=v2.6.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: website
          push: true
          tags: bjd2385/astrobot:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
