name: Publish Python package to PyPI

on:
  release:
    branches:
      - master

  workflow_dispatch:

jobs:
    build-and-publish:
      name: Build and publish astronautcount
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@master
          - name: Initialize Python 3.9
            uses: actions/setup-python@v2
            with:
              python-version: 3.9
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
          - name: Build binary wheel and a source tarball
            run: python setup.py sdist
          - name: Publish a Python distribution to PyPI
            uses: pypa/gh-action-pypi-publish@release/v1
            with:
              user: __token__
              password: ${{ secrets.PYPI }}
              packages_dir: dist/
